---
abstract: 'Inflates symbols in application config'
author:
  - 'Peter Flanigan <pjfl@cpan.org>'
build_requires:
  Module::Build: 0.4004
  version: 0.88
configure_requires:
  Module::Build: 0.4004
  version: 0.88
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300033, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-InflateMore
provides:
  Catalyst::Plugin::InflateMore:
    file: lib/Catalyst/Plugin/InflateMore.pm
    version: v0.6.2
requires:
  Catalyst: 5.90010
  Data::Visitor: 0.08
  Path::Class: 0.16
  namespace::autoclean: 0.05
  version: 0.88
version: 0.6.2
