---
abstract: 'Inflates symbols in application config'
author:
  - 'Peter Flanigan,  C<< <Support at RoxSoft.co.uk> >>'
build_requires:
  MRO::Compat: 0.11
  Test::More: 0.74
configure_requires:
  Module::Build: 0.38
  version: 0.74
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-InflateMore
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  Catalyst::Plugin::InflateMore:
    file: lib/Catalyst/Plugin/InflateMore.pm
    version: v0.4.81
requires:
  Catalyst: 5.9001
  Data::Visitor: 0.08
  Path::Class: 0.16
  namespace::autoclean: 0.05
  perl: 5.01
  version: 0.74
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Catalyst-Plugin-InflateMore
  homepage: http://www.roxsoft.co.uk
  license: http://dev.perl.org/licenses/
version: 0.4.81
