---
abstract: 'Inflates symbols in application config'
author:
  - 'Peter Flanigan <pjfl@cpan.org>'
build_requires:
  Module::Build: 0.4004
  version: 0.88
configure_requires:
  Module::Build: 0.4004
  version: 0.88
dynamic_config: 1
generated_by: 'Dist::Zilla version 4.300033, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-InflateMore
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  Catalyst::Plugin::InflateMore:
    file: lib/Catalyst/Plugin/InflateMore.pm
    version: v0.7.1
requires:
  Catalyst: 5.90010
  Data::Visitor: 0.08
  Path::Class: 0.16
  namespace::autoclean: 0.05
  perl: 5.008
  version: 0.88
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Catalyst-Plugin-InflateMore
  homepage: https://metacpan.org/author/PJFL
  license: http://dev.perl.org/licenses/
version: 0.7.1
